config/routes.rb
Tasks::Application.routes.draw do

  devise_for :users, path: 'auth'
  resources :users
  resources :comments

  get 'tasks/project/:project_id' => 'tasks#index_by_project', as: 'project_tasks'
  get 'tasks/without_project' => 'tasks#index_wo_project', as: 'without_project_tasks'
  resources :tasks do
    namespace :status, module: 'tasks', controller: 'status' do
      post 'reopen'
      post 'start'
      post 'suspend'
      post 'finish'
    end
    resources :comments
  end

  resources :projects do
    post 'add_user'
    delete 'delete_user/:id', action: 'delete_user', as: 'delete_user'
    get 'new_task' => 'tasks#new'
    get 'tasks'
  end

  root 'welcome#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :owner, class_name: 'User'
  belongs_to :project

  has_many :comments, dependent: :destroy

  default_scope {order(created_at: :desc)}

  scope :all_for_user, ->(user) {
    project_ids = user.projects.pluck(:id)
    tasks = Task.includes(:project)
    tasks = tasks.where{((project_id == nil) & (owner_id == my{user.id}) ) | (project_id.in(project_ids))}
    return tasks
  }

  scope :without_project, -> {where(project_id: nil)}

  validates :title, presence: true
  validates :owner, presence: true

  # states: new, in_work, suspended, finished
  state_machine :state, initial: :new do
    event :start do
      transition to:  :in_work
    end

    event :suspend do
      transition to: :suspended
    end

    event :reopen do
      transition to: :new
    end

    event :finish do
      transition to: :finished
    end

    before_transition on: :finish do |task, transition|
      task.finished_at = Time.now
    end
  end

  def is_owner?(user)
    self.owner_id == user.id
  end

  def when_finished
    I18n.l finished_at, format: :short if state?(:finished) && finished_at
  end

  def when_created
    I18n.l created_at, format: :short
  end
end

app/controllers/tasks/status_controller.rb
class Tasks::StatusController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task
  before_action :is_project_member_or_own_task?

  def reopen
    @task.reopen
    redirect_to task_path(@task)
  end

  def start
    @task.start
    redirect_to task_path(@task)
  end

  def finish
    @task.finish
    redirect_to tasks_path
  end

  def suspend
    @task.suspend
    redirect_to task_path(@task)
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end

  def is_project_member_or_own_task?
    unless @task.is_owner?(current_user) or (@task.project and @task.project.is_member?(current_user))
      redirect_to tasks_path, alert: 'Нет доступа!'
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :is_own_task?, only: [:edit, :update, :destroy]
  before_action :is_project_member?, only: [:show]

  def index
    @project = :all
    @tasks = current_user.all_tasks
  end

  def index_by_project
    @project = current_user.projects.find(params[:project_id])
    @tasks = @project.tasks
    render :index
  end

  def index_wo_project
    @project = :empty
    @tasks = current_user.tasks.without_project
    render :index
  end


  def show
    @comments = @task.comments
  end

  def new
    @task = current_user.tasks.new(project_id: params[:project_id])
  end

  def edit
  end

  def create
    @task = current_user.tasks.new(task_params)

    if @task.save
      redirect_to tasks_path, notice: 'Задача успешно добавлена.'
    else
      render action: 'new'
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_url, notice: 'Задача успешно обновлена.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def is_own_task?
      redirect_to(tasks_path, alert: 'Нет доступа!') unless @task.is_owner?(current_user)
    end

    def is_project_member?
      if @task.project and not @task.project.users.include?(current_user)
        redirect_to tasks_path, alert: 'Нет доступа!'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :project_id, :state)
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
  def project_link_to(active, *options)
    li_class = "project-link#{' active' if active}"
    content_tag :li, class: li_class do
      link_to *options
    end
  end
end

app/views/tasks/_form.html.haml
= form_for(@task, html: {role: 'form'}) do |f|
  - if @task.errors.any?
    .error_explanation
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-sm-9
      .form-horizontal
        .form-group
          = f.label :title, class: 'control-label col-sm-2'
          .col-sm-10
            = f.text_field :title, class: 'form-control', autofocus: true
        .form-group
          = f.label :description, class: 'control-label col-sm-2'
          .col-sm-10
            = f.text_area :description, rows: 10,  class: 'form-control wysihtml5'
    .col-sm-3
      .form-group
        = f.submit class:'btn btn-default pull-right'
        %br
        %br
      .form-group
        =f.label :state, 'Статус:', class: 'control-label'
        - %w(new in_work suspended finished).each do |state|
          - state_sym = state.to_sym
          .radio
            = f.label "state_#{state}".to_sym do
              = f.radio_button :state, state_sym, checked: @task.state?(state_sym)
              = Task.human_state_name(state_sym)
      .form-group
        = f.label :project_id, class: 'control-label'
        = f.collection_select :project_id, current_user.projects, :id, :title, {include_blank: 'Без проекта'}, {class: 'form-control'}
      

app/views/tasks/_projects_list.html.haml
%ul.nav.nav-pills.nav-stacked
  =project_link_to (@project == :all), 'Все задачи', tasks_path
  =project_link_to (@project == :empty), 'Без проектов', without_project_tasks_path
  - current_user.projects_sorted.each do |project|
    =project_link_to (@project == project), project.title, project_tasks_path(project)

app/views/tasks/_task_list.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title
      Все задачи:
      =link_to new_task_path, class: 'btn btn-default btn-xs pull-right' do
        %span.glyphicon.glyphicon-plus
        Добавить задачу    
  %table.table.table-striped.table-hover.hide-buttons
    %thead
      %tr
        %th.col-sm-5 Наименование
        %th.col-sm-2 Проект
        %th.col-sm-1 Статус
        %th.col-sm-2 Создано
        %th.col-sm-2 Завершено
    %tbody
      = render partial: 'tasks', locals: {tasks: tasks}

app/views/tasks/_tasks_list.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title
      &nbsp
      =link_to ([:all, :empty].include?(@project) ? new_task_path : project_new_task_path(@project) ),
                class: 'btn btn-default btn-xs pull-right' do
        %span.glyphicon.glyphicon-plus
        Добавить задачу    
  %table.table.table-striped.table-hover.hide-buttons
    %thead
      %tr
        %th{class: (@project == :all ? 'col-sm-5' : 'col-sm-7')} Наименование
        - if @project == :all
          %th.col-sm-2 Проект
        %th.col-sm-1 Статус
        %th.col-sm-2 Создано
        %th.col-sm-2 Завершено
    %tbody.rowlink{'data-link'=>'row'}
      - tasks.each do |task|
        %tr
          %td
            - if task.is_owner?(current_user)
              =link_to edit_task_path(task), class:'pull-right button' do
                %span.glyphicon.glyphicon-pencil
            =link_to task.title, task_path(task)
          - if @project == :all
            %td.rowlink-skip
              - if task.project
                =link_to task.project.title, project_path(task.project)
          %td=task.human_state_name
          %td=task.when_created
          %td=task.when_finished

app/views/tasks/edit.html.haml
.page-header
  %h1 Редактирование задачи
=render partial: 'form'

app/views/tasks/index.html.haml
.page-header
  %h1 Список задач
.row-fluid
  .col-sm-2.projects-list
    = render partial: 'projects_list'
  .col-sm-10.task-list
    = render partial: 'tasks_list', locals: { tasks: @tasks }
    

app/views/tasks/new.html.haml
.page-header
  %h1 Новая задача
=render partial: 'form'

app/views/tasks/show.html.haml
.page-header
  %h1
    =@task.title
    - if @task.is_owner?(current_user)
      =link_to edit_task_path(@task), class: 'btn btn-default btn-sm pull-right' do
        %span.glyphicon.glyphicon-pencil
      =link_to task_path(@task), confirm: 'Вы точно хотите удалить эту задачу?', method: :delete,
                                        class: 'btn btn-default btn-sm pull-right' do
        %span.glyphicon.glyphicon-trash
.row
  .col-sm-10
    - unless @task.is_owner? current_user
      %p
        %b Автор:
        = @task.owner.name
    %p
      %b Создано:
      = l @task.created_at, format: :long
    %p
      %b Статус:
      = @task.human_state_name
    %p
      = raw @task.description
  .col-sm-2
    .btn-group
      - case (@task.state)
        - when 'new'
          =link_to 'Начать', task_status_start_path(@task), method: :post, class: 'btn btn-primary'
        - when 'in_work'
          =link_to 'Завершить', task_status_finish_path(@task), method: :post, class: 'btn btn-primary'
        - when 'finished', 'suspended'
          =link_to 'Возобновить', task_status_reopen_path(@task), method: :post, class: 'btn btn-primary'
      %button.btn.btn-primary.dropdown-toggle{data:{toggle:'dropdown'}}
        %span.caret
      %ul.dropdown-menu{role:'menu'}
        %li=link_to 'Начать', task_status_start_path(@task), method: :post
        %li=link_to 'Завершить', task_status_finish_path(@task), method: :post
        %li=link_to 'Возобновить', task_status_reopen_path(@task), method: :post
        %li=link_to 'Отложить', task_status_suspend_path(@task), method: :post
  =render '/comments/comments_list'
  =render '/comments/comment_form'
  