config/routes.rb
Tasks::Application.routes.draw do

  devise_for :users, path: 'auth'
  resources :users
  resources :comments

  get 'tasks/project/:project_id' => 'tasks#index_by_project', as: 'project_tasks'
  get 'tasks/without_project' => 'tasks#index_wo_project', as: 'without_project_tasks'
  resources :tasks do
    namespace :status, module: 'tasks', controller: 'status' do
      post 'reopen'
      post 'start'
      post 'suspend'
      post 'finish'
    end
    resources :comments
  end

  resources :projects do
    post 'add_user'
    delete 'delete_user/:id', action: 'delete_user', as: 'delete_user'
    get 'new_task' => 'tasks#new'
    get 'tasks'
  end

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %w(admin user)

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :role, presence: true, inclusion: {in: ROLES}
  validates :email, presence: true
  validates :name, presence: true

  has_many :tasks, foreign_key: :owner_id
  has_and_belongs_to_many :projects
  has_many :comments, dependent: :destroy
  
  ROLES.each do |role|
    define_method "is_#{role}?" do
      self.role == role
    end
  end

  def own_projects
    self.projects.where(projects:{owner_id: self.id})
  end

  def anothers_projects
    self.projects.where.not(projects:{owner_id: self.id})
  end

  def projects_sorted
    self.projects.order("(owner_id = #{self.id}) DESC")
  end

  def all_tasks
    Task.all_for_user(self)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private
    def check_admin!
      unless current_user.is_admin?
        flash[:alert] = "Доступ запрещен!"
        redirect_to root_url
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      if current_user.is_admin?
        params.require(:user).permit(:name, :role, :email, :password)
      else
        params.require(:user).permit(:name, :email)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for(@user, html: {role: 'form', class: 'form-horizontal'}) do |f|
  - if @user.errors.any?
    .error_explanation
      %h2 #{pluralize(@user.errors.count, "error")} prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, 'Имя', class: 'control-label col-sm-1'
    .col-sm-6
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, class: 'control-label col-sm-1'
    .col-sm-6
      = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :role, 'Роль', class: 'control-label col-sm-1'
    .col-sm-6
      = f.select :role, options_for_select([['Админ', 'admin'],['Не админ', 'user']], @user.role || 'user'), {},
                                                                                    class: 'form-control'
  - if @user.new_record?
    .form-group
      = f.label :password, 'Пароль', class: 'control-label col-sm-1'
      .col-sm-6
        = f.text_field :password, class: 'form-control'
  .form-group
    = f.submit class:'btn btn-default'

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.haml
.page-header
  %h1 Пользователи
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Имя
      %th email
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.name, user_path(user)
        %td= user.email
        %td
          = link_to edit_user_path(user) do
            %span.glyphicon.glyphicon-pencil
        %td
          = link_to user, method: :delete, confirm: "Вы действительно хотите удалить пользователя '#{user.name}'" do
            %span.glyphicon.glyphicon-trash

= link_to 'Добавить пользователя', new_user_path, class: 'btn btn-default'

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>