config/routes.rb
Tasks::Application.routes.draw do

  devise_for :users, path: 'auth'
  resources :users
  resources :comments

  get 'tasks/project/:project_id' => 'tasks#index_by_project', as: 'project_tasks'
  get 'tasks/without_project' => 'tasks#index_wo_project', as: 'without_project_tasks'
  resources :tasks do
    namespace :status, module: 'tasks', controller: 'status' do
      post 'reopen'
      post 'start'
      post 'suspend'
      post 'finish'
    end
    resources :comments
  end

  resources :projects do
    post 'add_user'
    delete 'delete_user/:id', action: 'delete_user', as: 'delete_user'
    get 'new_task' => 'tasks#new'
    get 'tasks'
  end

  root 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :owner, class_name: 'User'
  has_and_belongs_to_many :users
  has_many :tasks, dependent: :destroy

  validates :title, presence: true, uniqueness: {scope: :owner }

  def is_owner?(user)
    self.owner_id == user.id
  end

  def is_member?(user)
    self.users.include? user
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy, :add_user, :delete_user]
  before_action :check_owner, only: [:edit, :update, :destroy, :add_user, :delete_user]

  def index
    @own_projects = current_user.own_projects
    @projects = current_user.anothers_projects
  end

  def show
    @tasks = @project.tasks
  end

  def new
    @project = current_user.projects.new
  end

  def edit
  end

  def create
    @project = current_user.projects.new(project_params)
    @project.owner = current_user
    if @project.save
      @project.users << current_user
      redirect_to project_tasks_path(project_id: id), notice: 'Проект успешно создан.'
    else
      render action: 'new'
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Проект успешно обновлен.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Проект успешно удален.'
  end

  def add_user
    @project = current_user.projects.find(params[:project_id])
    @user = User.find_by email: params[:email]
    if @user
      if @project.users.find_by id: @user.id
        redirect_to @project, alert: 'Пользователь уже в проекте.'
      else
        @project.users << @user
        redirect_to @project, notice: 'Пользователь добавлен.'
      end
    else
      redirect_to @project, alert: 'Пользователь с таким email не найден'
    end
  end

  def delete_user
    @project = current_user.projects.find(params[:project_id])
    @user = User.find(params[:id])
    if @user
      if @project.users.find_by id: @user.id
        @project.users.delete(@user)
        redirect_to @project, notice: 'Пользователь удален'
      else
        redirect_to @project
      end
    else
      redirect_to @project, alert: 'Пользователь не существует'
    end
  end

  def tasks
    project = current_user.projects.find(params[:project_id])
    render partial:'projects/tasks/list', locals: {project: project}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      if params[:project_id]
        @project = current_user.projects.find(params[:project_id])
      else
        @project = current_user.projects.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title)
    end

    def check_owner
      unless @project.is_owner?(current_user)
        redirect_to projects_path, error: 'Недостаточно прав!'
      end
    end
end

app/views/projects/_form.html.haml
.col-sm-7
  = form_for(@project, html: {role: 'form'}) do |f|
    - if @project.errors.any?
      .error_explanation
        %ul
          - @project.errors.full_messages.each do |msg|
            %li= msg
    .form-group
      = f.label :title, class: 'control-label col-sm-2'
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.submit class:'btn btn-default pull-right'

app/views/projects/_tasks_list.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title
      Список задач проекта:
      =link_to project_new_task_path(project_id: project.id), class: 'btn btn-default pull-right btn-xs' do
        %span.glyphicon.glyphicon-plus
        Добавить задачу

  %table.table.table-striped.table-hover.hide-buttons
    %thead
      %tr
        %th.col-sm-2 Автор
        %th Наименование
        %th.col-sm-1 Статус
        %th.col-sm-2 Cоздано
        %th.col-sm-2 Завершено
    %tbody
      - tasks.each do |task|
        %tr
          %td=task.owner.name
          %td
            =link_to task.title, task_path(task)
            - if task.is_owner?(current_user)
              =link_to edit_task_path(task), class:'btn btn-xs' do
                %span.glyphicon.glyphicon-pencil            
          %td=task.human_state_name
          %td=task.when_created
          %td=task.when_finished

app/views/projects/_users_list.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Участники проекта:
  .panel-body
    %ul
      - project.users.each do |user|
        %li
          = user.name
          - if project.is_owner?(current_user) and not project.is_owner?(user)
            = link_to project_delete_user_path(project, user), data: {confirm: "Вы точно хотите удалить пользователя #{user.name} из проекта?"}, method: :delete, class: 'btn btn-default btn-xs' do
              %span.glyphicon.glyphicon-trash
    - if project.is_owner? current_user
      %p
        = form_tag(project_add_user_path(project), class: 'form-inline') do
          = label_tag :email
          = email_field_tag :email
          = submit_tag 'Добавить', class: 'btn btn-primary'

app/views/projects/edit.html.haml
=render partial: 'form'

app/views/projects/index.html.haml
.page-header
  %h1 Проекты
%p
  - if @own_projects.size > 0
    %ul
      - @own_projects.each do |project|
        %li
          =link_to project.title, project_path(project)
  - else
    У вас все еще нет своих проектов
- if @projects.size > 0
  %p
    %h4 Проекты в которых принимаете участие:
    %ul
      - @projects.each do |project|
        %li
          =link_to project.title, project_path(project)

=link_to new_project_path, class: 'btn btn-default' do
  %span.glyphicon.glyphicon-plus
  Добавить проект

app/views/projects/new.html.haml
.page-title
  %h1 Новый проект
=render partial:'form'

app/views/projects/show.html.haml
.page-title
  %h1
    =@project.title
    - if @project.is_owner?(current_user)
      =link_to edit_project_path(@project), class: 'btn btn-default btn-sm pull-right' do
        %span.glyphicon.glyphicon-pencil
      =link_to project_path(@project), data: {confirm: 'Вы точно хотите удалить этот проект?'}, method: :delete,
                                        class: 'btn btn-default btn-sm pull-right' do
        %span.glyphicon.glyphicon-trash
%br
.row
  .col-sm-8
    = render partial: 'tasks/tasks_list', locals: {tasks: @tasks, project: @project}
  .col-sm-4
    = render partial: 'users_list', locals: {project: @project}