config/routes.rb
Tasks::Application.routes.draw do

  devise_for :users, path: 'auth'
  resources :users
  resources :comments

  get 'tasks/project/:project_id' => 'tasks#index_by_project', as: 'project_tasks'
  get 'tasks/without_project' => 'tasks#index_wo_project', as: 'without_project_tasks'
  resources :tasks do
    namespace :status, module: 'tasks', controller: 'status' do
      post 'reopen'
      post 'start'
      post 'suspend'
      post 'finish'
    end
    resources :comments
  end

  resources :projects do
    post 'add_user'
    delete 'delete_user/:id', action: 'delete_user', as: 'delete_user'
    get 'new_task' => 'tasks#new'
    get 'tasks'
  end

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_alert_type_for(flash_type)
    case flash_type
      when :success
        "success"
      when :error
        "danger"
      when :alert
        "warning"
      when :notice
        "info"
      else
        flash_type.to_s
    end
  end

  def flash_message(flash)
    return nil if flash.empty?
    flash.map do |type, message|
      {
        message: { text: message },
        type: bootstrap_alert_type_for(type)
      }
    end
  end
end

app/views/application/_admin_menu.html.haml
%li
  =link_to "Пользователи", users_path

app/views/application/_login_items.html.haml
- if user_signed_in?
  %li
    = link_to 'Выйти', destroy_user_session_path, method: :delete
- else
  %li
    = link_to 'Войти', new_user_session_path
  %li
    = link_to 'Зарегистрироваться', new_user_registration_path

app/views/application/_user_menu.html.haml
%li
  =link_to "Задачи", tasks_path